### ISSUE TITLE
Source code documentation & tests

### ISSUE THREAD

**Issue by darthdeus** [LightTable/LightTable#1038]
*I made this into an issue instead of posting it on the mailing list, because in my mind this is an issue and not just a discussion :)*

I've started writing a Ruby plugin (so far I've got some basic things working) and now that I'm trying to implement the eval part, I've found myself struggling to navigate the source code, as I'm pretty new to clojure. Which leads me to two things:

I'd love to start adding inline docs (at least some to the most obvious places), unless someone plans to document everything by themself :)

And then there's the question of unit tests. Since ClojureScript is a super-dynamic language it's not really a question (at least in my mind) whether we should have tests for at least the non-UI stuff. But it's probably a good idea to get some general agreement on how to approach this, what library to use, etc.

**Comment by kenny-evitt** [comment]
I'm going to close this, not because it's not a good idea (or two good ideas) – it is (they are) – but because it's not really useful as an open issue.

I'm willing to accept PRs on the *atom-shell* branch for adding comments or other source code documentation.

I'd like to add tests – I just tried to add [clojurescript.test](https://github.com/cemerick/clojurescript.test) – see [this comment](https://github.com/LightTable/LightTable/pull/1921#issuecomment-113599511) related to a small change for which it would be nice to have a few corresponding tests.

But I ran into an issue with clojurescript.test that was (somewhat) fixed, but in versions that require newer versions of ClojureScript. Unfortunately, per #1739 we may not be able to do so that soon:

 - [Update ClojureScript dependency · Issue #1739 · LightTable/LightTable](https://github.com/LightTable/LightTable/issues/1739)

And we may not be able to add tests – see #1647 for the first documented attempt:

 - [Adding a test suite to Light Table · Issue #1647 · LightTable/LightTable](https://github.com/LightTable/LightTable/issues/1647)

[Or, maybe we will need "to run the tests in LT itself".](https://github.com/LightTable/LightTable/issues/1647#issuecomment-58197749) That's an interesting idea actually ...
