### ISSUE TITLE
Inline eval doesn't happen if a falsey value is on a line by itself

### ISSUE THREAD

**Issue by brandonbloom** [LightTable/LightTable#1060]
```clojure
(identity "you can cmd+enter on this")

false ; or nil

(identity "but not here!")
```

**Comment by kenny-evitt** [comment]
As mentioned in [this comment](https://github.com/LightTable/LightTable/issues/1665#issuecomment-62507373) on a related issue, this is probably due to something with the InstaREPL not evaluating, or not displaying the results of evaluating, certain forms.

I can reproduce a similar behavior for string literals:

```
"blah blah blah"       ;; This doesn't seem be evaluated

(str "blah blah blah") ;;=> "blah blah blah"
```

However, the string literal doesn't prevent *subsequent* forms from being evaluated.

**Comment by cldwalker** [comment]
This issue has moved to https://github.com/LightTable/ClojureInstarepl/issues/3 as the instarepl is its own plugin
