### ISSUE TITLE
Saving/restoring workspace 

### ISSUE THREAD

**Issue by fjarri** [LightTable/LightTable#1131]
Is there currently a way to save current workspace in a file (similar to .sublime-project files in ST) and later restore it? The closest thing I can find is "open recent workspace" command, so if I work on several different projects I have to assemble the workspace manually every time.

In general, it would be very convenient to have some language-independent way to describe a collection of files a user is working on. I personally like the "blacklisting" ST approach, where you specify the list of folders and the files that you want to exclude from the project (e.g. build files), and the rest shows up in the project pane automatically.

**Comment by kenny-evitt** [comment]
@cldwalker I'm actually interested in this, or something similar. But I don't think there's much use in keeping this issue open. We should probably move this to the wishlist. Or maybe I'm wrong – maybe there's significant utility in leaving issues like this open for the community to discuss until someone creates a separate repo for a plugin? @rundis Thoughts? Preferences?

What I'd like personally is to be able to have any number of workspaces. [The existing code actually deletes workspace files if there are more than 20.](https://github.com/LightTable/LightTable/blob/master/src/lt/objs/workspace.cljs#L189-L194) I'd also like to be able to open a workspace from the file navigation sidebar (or a separate sidebar that opens in the same location and behaves similarly).

For anyone interested, LT is saving workspaces as files in [the user directory](https://github.com/LightTable/LightTable/issues/1968) sub-directory */ltcache/workspace*.

@fjarri Still interested in this?

**Comment by fjarri** [comment]
@kenny-evitt: Yes, for me it's still a critical feature (and pretty much the only the reason I still use ST). Also, as I mentioned in the comments above, LT workspaces are not quite what I mean by project files (unless something has changed in two years). In fact, if you have a project file, you can put the workspace file alongside it, eliminating any need for some artificial limit on the number of such files.

**Comment by kenny-evitt** [comment]
@fjarri What if we added a command to open a workspace from a file, i.e. not just the workspace files LT manages now?

I think this would work great for what I was imagining too. I like to organize my ad-hoc scripts, code files, and notes by issue from my issue tracker. It would be nice if I could save a workspace for each issue that includes any folders specific to the issue as well as folders for the relevant code repos.

I think, because LT behaviors can be defined for a workspace, you should be able to exclude specific files or directories easily.

Some other related changes that seem appropriate:

 - Remove the 20 workspace limit.
 - Add names for workspaces. Right now workspaces are just shown (in the open-a-recent-workspace list) as a list of the folders they contain.
 - Add some kind of (auto-complete) search for workspaces by name (or by name of filer or folder contained within).
 - Visually distinguish between 'project' workspaces and LT workspaces, maybe just by showing the full path of project workspace files but only the file name of the LT workspaces.
 - Add a command to save an LT workspace as a project workspace file.
 - Add a command to save a project workspace as an LT workspace.

**Comment by fjarri** [comment]
I'm not sure I fully understand: what is the difference between project workspaces and LT workspaces? Does the former contain the project metadata (included folders, ignore masks, possibly build commands etc) and the latter contain the editor state (open files, breakpoints, monitored variables etc)? Or is it something else?

**Comment by kenny-evitt** [comment]
In my comment, by 'project workspace', I just meant a workspace stored in a file in the root directory of a 'project' (whatever that is).

They would contain included directories but not (yet, anyways) any of the other info you mention. At first, they would contain exactly the same info as the existing workspaces.

I'm proposing an incremental change in the direction of what you seem to be requesting. I'm ambivalent about whether the other info you describe should be part of the core workspace features.

**Comment by cldwalker** [comment]
Closing as LT auto-saves workspaces and allows you to restore them. To create a workspace, run the `Create new workspace` command. To restore a workspace, run the `Open recent workspace` and pick the one to restore. Workspaces can have multiple files and folders. No one else has shown interest in restoring through .sublime* style files. Feel free to add that to the wishlist - https://github.com/LightTable/LightTable/wiki/Feature-wishlist

**Comment by kenny-evitt** [comment]
@fjarri I'm still interested in this but I don't have the bandwidth to work on this for a while. We can re-open this issue if you or anyone else is interested in working on it.

One thing that just occurred to me that's a little tricky is how LT finds "project workspace files" given that LT only 'knows' about files and folders because they're in one of its workspaces.

**Comment by fjarri** [comment]
@kenny-evitt I'm afraid I won't be able to dedicate much time to it myself. I created this issue in hope to estimate the amount of people who would like to have this feature, but it seems I'm an outlier. For me it is something very convenient given my workflow (several projects kept on cloud drives and computational clusters, so keeping the project metadata along with the project files is important), but apparently most people do not feel this way.

**Comment by kenny-evitt** [comment]
@fjarri Feel free to continue commenting on this issue if you think of anything about this, or if you ever decide to work on it.

And, regardless of how much time you can dedicate to it, we can still make stead (if very slow) progress. Let's think in terms of the minimal sequence of changes that we'd like to see, particularly changes that are useful in-and-of-themselves.

If we just use the existing LT workspace file format, what's the minimal UI change that would be useful? Maybe just adding a new command "Workspace: Load a workspace from a file" would be sufficient.

**Comment by arozhok** [comment]
I added [:app :lt.objs.app/run-on-init [:workspace.show]] to user behaviors and installed the Reminisce plugin via plugin manager. Reopens both the workspace and tabs with the previously open files

**Comment by MarcelHekkert** [comment]
Great solution @arozhok Works nicely.
