### ISSUE TITLE
Tabsets don't properly resize after removing one of them

### ISSUE THREAD

**Issue by Morgawr** [LightTable/LightTable#1165]
How to replicate:

Open one extra tabset (aka 2 total), open some files in the first tabset, open some other files in the second tabset. Now add a third tabset and then remove it. The second tabset takes roughly two thirds of the screen while the first one takes only one third, whereas they should be resized to take 50/50.

**Comment by dosmoc** [comment]
I ran across this issue using the *atom-shell* branch on Windows 7; behaves as described in the original ticket. It can be reproduced with only one new file:

1. Open LightTable
2. ctrl-n to open a new file
3. Move the new file to a second tabset
4. Move the new file to a third tabset

At this point you get two tabsets 1/3 of the screen width, with an empty gray space:
![tabset_bug](https://cloud.githubusercontent.com/assets/2172829/8380610/a6c48ab8-1bdb-11e5-872b-b08ce2d4943d.png)

Removing the third tabset gets you the situation described in the original description of the issue:

![tabset_bug2](https://cloud.githubusercontent.com/assets/2172829/8380673/e3fe42d4-1bdb-11e5-8bfc-889690f366a0.png)

**Comment by dosmoc** [comment]
Interesting. There are two empty tabsets where the gray area is. If you move a file into the empty tabset, you can run the Remove active tabset command to remove it, and the tabsets return to what you might expect to see in terms of space. I think it behaves as intended, except there isn't any real visual indication that you have an open tabset so it can be a little confusing. Maybe a visual indicator that you can remove a tabset would help. Otherwise, one might think that closing all the tabs in a tabset should close the tabset.

**Comment by dosmoc** [comment]
After re-reading the original comment, it seems it's about about open tabsets not recovering space after tabsets are closed. If that's correct, I've actually failed to reproduce the problem, but at least I've finally watched the video about tabsets.
