### ISSUE TITLE
Workspace opening / closing bugs

### ISSUE THREAD

**Issue by markjfisher** [LightTable/LightTable#1217]
With the latest check in for pull request #1138 we can remove items from workspace (yay). However, it's got a few bugs.

**Removed elements still showing in list**
If you start lighttable, open a workspace and immediately right-click one of the folders and select "remove from workspace" it doesn't get removed from the list.

If you restart lighttable, and re-open the workspace, the folder you previously deleted is gone.

I've had similar results doing following:
- open workspace with 1 dir
- add another dir
- try to remove the first dir from list (fails) - still in list
- bounce lighttable, and reload workspace
- removed dir now gone.

**Adding folders to list don't show**
when you are first choosing a workspace to open, you get the list to pick from. Instead of picking one, if you right-click and choose "add folder" it isn't shown anywhere until you choose the workspace from the list.

**Duplicate Folders**
Not sure if this is supposed to be a feature, but the same dir can be added multiple times to a workspace.

**Comment by cldwalker** [comment]
Looking through old issues and came across this. About each issue:
1. Not reproducible on osx 10.10 with latest LT trying the first approach
2. I think this is reasonable behavior. If a user is picking a workspace, a right click behavior doesn't imply a decision has been made about picking a workspace
3. Duplicate folders and files has been fixed in #1689 

I'll close in a few days unless there's more info to make issue 1 reproducible

**Comment by cldwalker** [comment]
Closing but can reopen if given reproducible steps for the first issue
