### ISSUE TITLE
Light Table's main menu is not shown in Archlinux 64bit.

### ISSUE THREAD

**Issue by vagra** [LightTable/LightTable#1250]
I using 64bit Archlinux, when I click the main menu,  the drop-down menu was below the main view.
 
![snap_001](https://f.cloud.github.com/assets/1576687/2107277/88631674-8fc4-11e3-8590-659096a262a9.png)

when I right-click the desktop to shown the context menu, the context menu was below the main view.

![snap_002](https://f.cloud.github.com/assets/1576687/2107278/88f51ca4-8fc4-11e3-8819-bff8e04b055a.png)

**Comment by Faldrian** [comment]
LightTable also has a problem with virtual desktops on linux ... when you switch desktops, the window will stay on screen. If I switch applications, the window will stay on screen. Almost as if the content-window (which lags a bit behind when dragging the window) has a "show me top first always! On this physical window!" property, ignoring everything the window manager is telling the application.

**Comment by johnnzz** [comment]
I'm having this problem as well although, interestingly, it was working fine previously.

It isn't clear if the problem was triggered by an update, additional sw, or just whatever.  Basically, I was working, closed LT, then restarted it and presto-no-menus.

If I move the LT window with the menu selected, you can see the outline of the window, so like has been suggested, it seems like the menu is rendered behind the window.

I'm running a 64-bit Xubuntu 14.10 virt (XFCE/xfwm4 w/guest additions, 4GB RAM,64MB  vid mem, 3d accel enabled) in a Win7 64-bit host (VirtualBox 5 beta2, 16GB RAM, GeForce GT 640).  Host has three monitors, but virt uses two (L=1920x1160, R=1920x1200).  Problem occurs in both seamless and fullscreen configurations.

Over all the system is pretty stock Xubuntu.  Most notable is I run xfce-theme-manager to tweak the window decorations.  My system has some KDE and Gnome components installed as I tend to pick and choose specific desktop applications.

-john

**Comment by johnnzz** [comment]
So just the process of posting made me think... hmm.. rendering issue... 3d accel enabled... hmm.  So I shut down, de-selected 3d rendering acceleration in my virt, booted, and presto-menu-workie.

So, it's a sample size of one time, but it feels likely that this is the general area of the issue.

-john

**Comment by exitface** [comment]
@johnnzz This fixed it for me as well - thanks

**Comment by kenny-evitt** [comment]
@vagra @richardrasu @Sh4rK @standfest @Faldrian does the workaround mentioned by @johnnzz – disabling "3D rendering acceleration" – resolve this for any of you?

**Comment by Faldrian** [comment]
@kenny-evitt Sorry, I switched to another editor in the meantime.

**Comment by richardrasu** [comment]
@kenny-evitt Hi, not sure - have updated OS in the meantime.. Will give it a go (hopefully even soon), and reply when I can. Thanks,

**Comment by Maddix** [comment]
Linux mint 17 64 bit in virtual box also has this issue. The 32 bit works though.

1. Nvidia Quadro K2000M
2. Virtual box drivers (Vbox version 5.0.0)
3. No
4. No

**Comment by cldwalker** [comment]
On a Ubuntu 64bit on virtual box running LT 0.8.0-alpha, I'm also not seeing this issue.
Given there is a solution for this, disable 3D rendering, and no one who is effected has helped with a more general solution, I'm closing this. Feel free to add this to [the wishlist](https://github.com/LightTable/LightTable/wiki/Feature-wishlist#general). Happy to reopen if someone is working on a general solution wants to discuss more
