### ISSUE TITLE
Tab indenting adds additional space 

### ISSUE THREAD

**Issue by palfrey** [LightTable/LightTable#1516]
I've installed the Whitespace plugin to be able to better demonstrate the problem, but it occurred before installing that. `(:lt.objs.editor/tab-settings true 4 4)` is enabled in user behaviour.

Reproduction step: With 0.6.6 (also seen in 0.6.5 and possibly before), and cursor at end of tab-indented line, press return
![screen shot 2014-06-08 at 11 20 37 pm](https://cloud.githubusercontent.com/assets/38532/3212406/26908124-ef5b-11e3-81e1-0ccc47f6b2ee.png)

Observed behaviour: New line is indented by a) one less tab than I expected and b) a random space has been appended
![screen shot 2014-06-08 at 11 19 10 pm](https://cloud.githubusercontent.com/assets/38532/3212403/f5de2798-ef5a-11e3-9245-4157ca465c0b.png)

I can of course just press tab now, and my cursor will be where I want it, but we've then got a mixed tab/spaces layout which is not nice. I've been pondering this for a while, but can't seem to persuade Light Table to only indent with tabs. Is there anyway to do this?

**Comment by cldwalker** [comment]
Looking through old unanswered issues and found this. We get our syntax highlighting from CodeMirror. I don't have an issue with the following:

```clj
(ns foo
  (:require [foo1]
			[foo2]
			[foo3]))
```

First I'd recommend trying [the CodeMirror demo](http://codemirror.net/mode/clojure/index.html) and trying your use case. Since the demo doesn't have your indentation config, you'll need to modify it in your js console:
```js
editor.options.indentWithTabs = true
editor.options.indentUnit = 4
editor.options.tabSize = 4
```
If it doesn't work there then the issue should be opened [upstream](https://github.com/CodeMirror/CodeMirror/issues). If it does, then paste it in here and see if we need to update your clojure mode

**Comment by palfrey** [comment]
Just re-tested with 0.8.0 and this appears fixed now.

**Comment by cldwalker** [comment]
Glad to hear it!
