### ISSUE TITLE
Enforce specific size for internal browser window

### ISSUE THREAD

**Issue by ath** [LightTable/LightTable#1835]
When writing HTML for wide screens with Bootstrap or Foundation it can be difficult to see the full page when the internal browser is opened in a separate tabset. Because in this case the browser window’s width is roughly just half of the screen, and thus columns begin to stack.

It would be great to have (additionally to the existing behaviour) a way to define a fixed size, such as 1920x1080, for the internal browser. This still would mean that left/right scrolling would be required, but at least parts of the page will be represented in the same way as they would in a browser which really has that size.

**Comment by cldwalker** [comment]
If you run the "add browser tab" command, your browser can open in a separate tab (not tabset) and is mostly full screen. If you need fullscreen you can run the "Toggle fullscreen" command. As for the fixed browser size, that could be useful but I don't think it belongs in LT. You can resize windows to specific sizes [example here](https://github.com/LightTable/LightTable/blob/bb6885a5849fca0c026103c7c0420f600529181a/src/lt/objs/app.cljs#L133-L134) but not individual tabs. You can write this as a command and add it to your User plugin. If you'd like more guidance on writing the command let me know. Otherwise I'll close the ticket soon

**Comment by cldwalker** [comment]
Closing but if you have questions on how write that command feel free to reach out to the [mailing list](https://groups.google.com/forum/#!forum/light-table-discussion)
