### ISSUE TITLE
plugin manager do not work

### ISSUE THREAD

**Issue by uranio-235** [LightTable/LightTable#1887]
hi there, I has downloaded LT 0.7.2, after press cmd+space and write "plugin", never become the plugin manager...

**Comment by rundis** [comment]
ctrl+space surely
Should be found under Plugins: Show plugin manager

Do you get an empty list when you press ctrl+space ? Find it hard to believe the command for the plugin manager should have disappeared.

**Comment by uranio-235** [comment]
does you need a screen shoot? It show EVERYTHING except plugins manager

**Comment by martinchooooooo** [comment]
Hey @uranio-235 

A screenshot would be great. Also what OS are you using?

Cheers

**Comment by TorHou** [comment]
I can confirm that the plugin manager doesn't seem to work on this version (LT version 0.7.2, binary version 0.8.4).

It seems to be the plugin server is down. I get the message:
`Failed to load resource: the server responded with a status of 502 (Bad Gateway): http://plugins.lighttable.com`

**Comment by martinchooooooo** [comment]
Going through the release history, the plugin server was deprecated in favour for using Github as of [0.7.0](http://lighttable.com/2014/11/19/light-table-070) here     3f900b4266809ae142f4b34d62b86170b97674b8 

So that's why plugins.lighttable.com returns a 502.

@TorHou Not sure what the issue might be, though it might be your build of Lighttable. Did you download it from lighttable.com or build from source?
Also @TorHou do you at least get the plugin manager to show? From what @uranio-235 says he doesn't get it showing the the command list

**Comment by TorHou** [comment]
@martinchooooooo 
I just downloaded it via Download button ("LightTableLinux64.tar.gz"). I am very confused now, because I tested it again and it works. I don't know what changed but it seems the error was on my end.

**Comment by kenny-evitt** [comment]
@TorHou re-open this if you run into this problem again.

@martinchooooooo thanks for your help!
