### ISSUE TITLE
Atom-shell has been renamed

### ISSUE THREAD

**Issue by hkjels** [LightTable/LightTable#1904]
Atom shell is now [electron](http://electron.atom.io); since atom-shell is still referenced in build-scripts, this branch is actually broken atm.

**Comment by kenny-evitt** [comment]
@hkjels thanks; there's already two pull requests for this:

 * [Electron name change: update for Linux references by miraleung · Pull Request #1899 · LightTable/LightTable](https://github.com/LightTable/LightTable/pull/1899)
 * [Update build scripts for atom-shell name change to electron by martinchooooooo · Pull Request #1892 · LightTable/LightTable](https://github.com/LightTable/LightTable/pull/1892)

**Comment by hkjels** [comment]
Why are none of these being pulled?

**Comment by kenny-evitt** [comment]
@hkjels the core contributors have been otherwise occupied (e.g. with their paying gigs). I'm working with them to get up to speed so I can help out. I'm hoping to make some progress on this soon. I've had to merge these PRs to get a build on my computer to work so I expect them to be merged. I just wanted to have one of the core contributors review them first.

**Comment by hkjels** [comment]
OK, great!

**Comment by kenny-evitt** [comment]
I just merged both PRs.
