### ISSUE TITLE
LT does not build on Windows

### ISSUE THREAD

**Issue by hiredgunhouse** [LightTable/LightTable#1988]
script/build.sh in line 24 contains a command:
```bash
node_modules/.bin/grunt download-electron
```
but the problem is that the grunt script file is named grunt.cmd and Cygwin does not pick up .cmd extension as executable file cause it does not seem to respect PATHEXT environment variable.
Anyway I believe that the line should not specify path to grunt a simply be:
```bash
grunt download-electron
```
This fix works for me on Windows, but I haven't tested it on Linux.
I can make a PR, but it's probably not worth it, plus testing the fix on Linux would be a good idea.

BTW. A side thing is that maybe it would be nice to have a CI build on Windows?

**Comment by kenny-evitt** [comment]
I don't have any problem running this in a Cygwin Terminal on two different Windows 7 boxes. What version of Windows are you on? What's the error or warning you're seeing when you run the build script?

**Comment by hiredgunhouse** [comment]
@kenny-evitt ok, it is something I will have to investigate further, on the initial run of script/build.sh there is this file deploy/electron/node_modules/.bin/grunt that somehow disappears later.
Ignore the problem for now and I'll get back to you with more details.

**Comment by hiredgunhouse** [comment]
@kenny-evitt I did investigate the problem and it seems that some an old version of Atom (0.155.0) installed via Chocolatey somehow interfered with the download-electron task. Anyway I did some cleanups and LT is building fine again.
You can close this issue, sorry for the false alarm.

**Comment by kenny-evitt** [comment]
@hiredgunhouse No worries! Thanks for following up.

**Comment by ZombieHippie** [comment]
This issue is still relevant to windows on https://github.com/LightTable/LightTable/commit/a8a4f2e05c0f2295b6e093e87bcb06ab6f2e0303

**Comment by kenny-evitt** [comment]
@ZombieHippie That's too bad; I don't pay no mind to zombies, nor hippies! And definitely not zombie hippies :smile: 

In all seriousness, you can't have my brains – and definitely not for free (or for some grass).

In much more all-encompassing seriousness, you should probably open a new issue and provide enough details for someone to reasonably reproduce the same problem you're having. This issue turned out to a non-issue, according to the person that opened it, so it's not clear how it could still be relevant, especially to someone else. [Don't get hung-up on the issue title – this isn't the clearinghouse for all build problems on Windows.]
