### ISSUE TITLE
Light Tables opens very slowly in Windows 10

### ISSUE THREAD

**Issue by akash-vartak** [LightTable/LightTable#1994]

**Comment by kenny-evitt** [comment]
Please read [the guidelines for contributing](https://github.com/LightTable/LightTable/blob/master/CONTRIBUTING.md), particularly [the section on reporting bugs](https://github.com/LightTable/LightTable/blob/master/CONTRIBUTING.md#bugs):

> When filing a bug on GitHub, please help us help you by including the following:

> * *Steps to reproduce the bug.*
> * Your operating system, LT and relevant plugin versions.
> * Relevant configuration in your user.keymap and user.behaviors.

In this case, the steps to reproduce seem obvious. [But generally it's helpful to be more detailed than you might deem necessary!]

Your operating system is obvious but it would be nice to know which version of LT you're running and what plugins, and what versions, are installed. I'm not sure what might be relevant in your configuration so don't worry about that unless you suspect something *is* in fact relevant.

Given all that, please try building the latest source and comment in this issue whether the built version of LT opens very slowly. Also, please quantity "slowly" in your next comment. Not knowing whether LT takes 30 seconds or 30 minutes to open, and not knowing the specs of your computer, it's hard to know how drastic this issue is for you, and potentially for others.

It'd also be nice if you would install [Process Explorer](https://technet.microsoft.com/en-us/sysinternals/bb896653.aspx) and use it to monitor the LT processes when you open it. I'm curious as to the reported resources it uses when starting up.

**Comment by akash-vartak** [comment]
ohk...thanks, and sorry I didn't know about the info to be given when reporting bugs.
Will get back ASAP.

**Comment by akash-vartak** [comment]
I am running Windows 10 on Lenovo S510P - IdeaPad
Light Table Version: 0.7.2
Binary Version:0.8.6
Plugins - none

It takes about a whole minute to open.
By open I mean, I see the LT window with the huge LIGHT TABLE text but my previous workspace window or the default 'welcome' window does'nt open for about a minute or half.


I am attaching two images I thought would help.
![screenshot 1](https://cloud.githubusercontent.com/assets/8259599/10107699/8808622e-63da-11e5-9165-a21125f85b78.png)
![screenshot 2](https://cloud.githubusercontent.com/assets/8259599/10107700/883cd522-63da-11e5-9e64-4bdcf101f3dc.png)

Thanks.

**Comment by kenny-evitt** [comment]
@akash-vartak No worries! And thanks for the extra info. A minute might just be how long LT needs to fully load on your computer. The version of LT you're running uses node-webkit (now NW.js) which uses Chromium so LT is pretty similar to (an older version of) Chrome. How long does Chrome take to startup? [I don't think this is a particularly good comparison; in part because Chrome typically uses background services and that probably helps startup times.]

You could try building the latest source version. It uses a different app framework, Electron, but that still uses Chromium, so LT might just be slow starting up on your computer.

Is LT slow once it's running?

**Comment by akash-vartak** [comment]
Thanks for the verbose explanation. LT is slow only at startup.
Chrome is pretty fast though.

**Comment by kenny-evitt** [comment]
I just installed Windows 10 on a new computer and LT doesn't open slowly.

@akash-vartak We just release 0.8.0. If you're still interested in fixing this, please download the new version and confirm whether you're still having this problem with that version.

**Comment by akash-vartak** [comment]
Sure, I'll try that, 
<h1>Thanks a ton!!</h1>

**Comment by akash-vartak** [comment]
I'll close the thread once I try out the new version :)
