### ISSUE TITLE
No connection prompt for new cljs editors 0.8.0-alpha

### ISSUE THREAD

**Issue by justintaft** [LightTable/LightTable#2015]
In Lighttable 0.8.0, i was able to:
* create a new file (not saving, just new file command)
* Set the syntax of the editor to clojurescript
* Use evaluate editor contents
This will then prompt for a connection, and allowed me to select Lighttable-ui

In Light table 0.8.0 alpha, instead of prompting for a connection, a browser tab is opened instead.

I am on osx 10.10.5

**Comment by cldwalker** [comment]
Hi Justin. This is behavior specific to the Clojure plugin 0.2.0. The only reason it differs for the above versions is because we point to the latest Clojure plugin with latest LT. To understand how cljs eval works now I'd recommend reading [this intro](https://github.com/LightTable/Clojure#clojurescript-workflows). If you'd like to revert to the old behavior of manually selecting, you can with [this behavior](https://github.com/LightTable/Clojure/blob/fefd3af8f1e72e464df32f7f89bf6b5c64491fed/src/lt/plugins/clojure.cljs#L190-L198) by setting it nil

**Comment by justintaft** [comment]
Thanks

**Comment by cldwalker** [comment]
Closing since this is resolved
