### ISSUE TITLE
doc search result not ordered by best match

### ISSUE THREAD

**Issue by joanis** [LightTable/LightTable#2048]
Searching "for" in the doc search (ctrl-shift-d aka C-D) will yield the "for" function as 11th result. As it's a perfect match, I believe it should come first. Noticed this behaviour during multiple searches. Other example: if I search for "let", I get "wrap-complete" first (which looks totally unrelated to me).
- OS version: Ubuntu 14.04 LTS
- LT version: 0.8.0-alpha (vanilla)

**Comment by cldwalker** [comment]
This seems reasonable and happy to take a contribution that puts an exact match ahead of other results. Since this is a Clojure plugin, a PR should be done against that repository. Here is [sorting for clojure docs](https://github.com/LightTable/Clojure/blob/fefd3af8f1e72e464df32f7f89bf6b5c64491fed/lein-light-nrepl/src/lighttable/nrepl/doc.clj#L38) and [for clojurescript docs](https://github.com/LightTable/Clojure/blob/fefd3af8f1e72e464df32f7f89bf6b5c64491fed/lein-light-nrepl/src/lighttable/nrepl/doc.clj#L94)

**Comment by mtbar131** [comment]
Hi,
I would like to work on this bug to fix it. I am a beginner in clojure and I think this will be a perfect place to start.

**Comment by kenny-evitt** [comment]
@mtbar131 Great! Take a look at the code and ask questions in comments here in this issue or in [the Gitter chat room](https://gitter.im/LightTable/LightTable).

**Comment by sbauer322** [comment]
This issue is resolved with the following pull request in the Clojure plugin https://github.com/LightTable/Clojure/pull/84.
