### ISSUE TITLE
LT alpha gives the wrong output 

### ISSUE THREAD

**Issue by rwobben** [LightTable/LightTable#2050]
Hello, 

Im doing the clojure koans with LT and Im stuck here 

(def giants
  (with-meta 'Giants
    {:league "National League"}))

"Or more succinctly with a reader macro"
  (= {:division "West"} (meta '^{:division "West"} 'Giants))

When I evulate this  LT says false 
where i open a lein repl and put in the same message the outcome is true 

Roelof

**Comment by rundis** [comment]
Hi !

I find it hard to believe that lein repl returns true here. (Especially since I tried it to be sure).
Of course it could be something with clojure versions or perhaps tools.reader, but I'm very doubtful that LT has anything to do with it.

If faced with something like this, try to break it down and see what each individual function returns.
When I eval `{:division "West", :line 1, :column 8}` I get `{:division "West", :line 6, :column 8}` 
Which of course isn't the same as `{:division "West"}`

**Comment by rwobben** [comment]
Correct, LT puts also this sort of things in it.
Here the output of lein repl : 

user=> (meta '^{:division "West"} 'Giants)
{:division "West", :line 1, :column 8}

(= {:division "West"} (meta '^{:division "West"} Giants))
true

**Comment by rundis** [comment]
heh intersting. 
I tried `(= {:division "West"} (meta '^{:division "West"} 'Giants))` (note the ' which was in you original comment),  In lein repl which produces false, however removing the quote as you show in your second statement does indeed yield true, but not so in LT.

`(meta '^{:division "West"} Giants)` in LT gives `{:line 3, :column 28, :end-line 3, :end-column 34, :division "West"}` Line and col depending on which editor line you eval in. So I suppose the LT nrepl middleware attaches some metadata when evaling.

Regardless I'm not sure whether we should consider this a bug or rather a feature/sideeffect of the LT middleware. I mean I can't think of any use-cases this would cause any problems worthy of concern.
