### ISSUE TITLE
seesaw and language docs

### ISSUE THREAD

**Issue by jipen** [LightTable/LightTable#2082]
Hello,

My OS is : Windows 7 32 bits.
I use:
- Clojure 1.7.0
- [Seesaw 1.4.5](https://github.com/daveray/seesaw)
- Leiningen 2.5.3
- Java JDK 1.8.0_66 

I can't find the doc for Seesaw keywords when I simply connect to my Clojure project (connect Clojure client and choosing the project.clj file):
When I try for instance to find "invoke-later" in the Language doc window, I obtain:
"Found 0 doc results"
On the other hand, when I evaluate my main file core.clj (Ctrl-Ret on the last line of the file) I can then obtain the doc for these keywords ("Found 4 doc results" for "invoke-later") while the application/connection is running.

Just as if the simple connection to the project didn't manage correctly the dependancies for docs...

P.S: I join my core.clj and project.clj files in a zip.
[MySeesawProject.zip](https://github.com/LightTable/LightTable/files/68587/MySeesawProject.zip)

**Comment by jipen** [comment]
Just to add a precision:
I'm able to find docs for Clojure keyword (such as "sort") in both cases: connect clojure client via project.clj or connection by evaluating the core.clj.

**Comment by carocad** [comment]
hey @jipen 
I don't think this is a bug. When you connect to the project you only established a connection to an nREPL but there is no namespace nor vars loaded from the dependencies, they were merely downloaded and put on the classpath.

Lighttable (actually Clojure's plugin) doesn't search inside the classpath nor on the files that were downloaded from the dependencies, but rather it defers that responsibility to the nREPL. Since the nREPL doesn't have any information about the namespaces that you are referring to then it reports to find no match.

Of course that changes, when you evaluate your main file, since at that point you bounded the dependencies to var names (via require, import or use). At that point the nREPL can find them and extract their metadata, which is where the docstring are.

Clojure's functions are special because they are all loaded when the nREPL starts. Because of that they can be found from the very beginning.

Hope it helps

**Comment by carocad** [comment]
@jipen if that solves your answer your issue please consider closing this issue. Thanks
