### ISSUE TITLE
JNDI Lookup Failed For Clojure Code.

### ISSUE THREAD

**Issue by neelspoc32** [LightTable/LightTable#2141]
I am trying eval a lookup clojure code in my editor.

`(@ (delay  {:datasource (yc/lookup-jndi "java:comp/env/jdbc/MDB")}))`

But it gives me an error saying -

```
javax.naming.NameNotFoundException: null
           NamingContext.java:505 org.eclipse.jetty.jndi.NamingContext.lookup
           NamingContext.java:536 org.eclipse.jetty.jndi.NamingContext.lookup
           NamingContext.java:551 org.eclipse.jetty.jndi.NamingContext.lookup
      javaRootURLContext.java:117 org.eclipse.jetty.jndi.java.javaRootURLContext.lookup
          InitialContext.java:411 javax.naming.InitialContext.lookup
                   common.clj:128 application-common.common/lookup-jndi
codepath\config.clj:256 application.config/eval18840[fn]
                    Delay.java:33 clojure.lang.Delay.deref
                    core.clj:2128 clojure.core/deref
codepath\config.clj:256 application.config/eval18840
```

Note - Path Names have been changed in error.
It works from the command prompt.The lookup-jndi code comes from a library.

**Comment by kenny-evitt** [comment]
@neelspoc32 What OS are you running? What version of LT are you using? And would you share a minimal example project with code with which you can reproduce this error?

Also, specific steps to reproduce this – and specific steps to observe that it "works from the command prompt" would be extremely helpful.

**Comment by rundis** [comment]
Where is the jndi entry defined. Typically you would do that in a container like jetty,tomcat, jboss or whatever ? Are you sure you have bootstrapped the jndi setup and if yes did you do it the context of the same repl connection you are trying to do the lookup evaluation from ? Say it's Jetty for arguments sake, did you start jetty through a repl connection in LT prior to trying to do the lookup?

As @kenny-evitt alludes to, you leave us very little to go by. 
Tbh I find it hard to understand how Lt is to blame for this by the minimal info we got. (Jndi entry not found... well maybe that's because it's not defined would be my first thought. My next thought might be why isn't it defined ? I really don't mean to be rude, but I fail to connect the dots that the obvious answer to the last question would be "because of light table" )

**Comment by neelspoc32** [comment]
hey, sorry for the trouble caused.I am not sure what was  the exact problem,but i reinstalled the light table , cleanup the temp files and set the proxy again and it seems to be working now.
