### ISSUE TITLE
Cannot scroll horizontally through open file tabs

### ISSUE THREAD

**Issue by henrywright** [LightTable/LightTable#2151]
If I open lots of files resulting in lots of tabs across the top of the screen, there seems to be no way to horizontally scroll through them.

I'm using Ubuntu 14.04 with Light Table 0.8.1.

**Comment by kenny-evitt** [comment]
This would be nice but I'm not sure there's an easy solution. Personally, I find that I often want to close tabs when I have more than a few open at once. The 'open file bar' provides a really easy way to open any file (for which I can remember the name, and for which there is some mostly-unique subset of text in that name).

Why are you opening "lots" of files simultaneously?

Are you willing to work on this yourself?

**Comment by henrywright** [comment]
> Why are you opening "lots" of files simultaneously?

I'm not really opening lots. I'm working on a smaller screen so don't have much real estate to play with.

It also depends on the names of the files I have open, longer file names seem to take up more space.

> Are you willing to work on this yourself?

Would love to but I don't have any ClojureScript experience :(

**Comment by kenny-evitt** [comment]
@henrywright Thanks for the feedback.

Maybe instead of scrolling the tab labels we could add an overlay that lists all the tab labels, e.g. after the user presses <kbd>Ctrl</kbd>+<kbd>Tab</kbd> and continues to hold <kbd>Ctrl</kbd>.

With regard to ClojureScript experince, you're in luck – we don't require any experience! You still have to write ClojureScript code tho :smile

More seriously, if no one expresses interst in working on this in the next few weeks, I'm going to move it to the feature wishlist.

**Comment by henrywright** [comment]
Thanks @kenny-evitt I think I can work around this because it's easy to click on a file in the file tree and jump to the appropriate tab.

**Comment by Trapets** [comment]
Maybe what you are looking for: `ctrl`+`shift`+`tab` and you can also define shortcuts for next and previous tab. Mouse over tabname and scroll.

**Comment by cldwalker** [comment]
On osx I can scroll fine on tabs horizontally by swiping left and right. In #1776 horizontal scrolling horizontally worked fine for another linux user. I'm closing as multiple alternate solutions have been proposed and that seems good enough in lieu of digging in more to the original issue
