### ISSUE TITLE
How to use a key other than tab for autocomplete?

### ISSUE THREAD

**Issue by mrobbetts** [LightTable/LightTable#2155]
I'm new to Light Table, and can't figure out how to use a key that isn't tab to summon autocomplete. Hopefully this is simple!

I am having literally the worst user experience ever, because most of the time when I press Tab, I just want to insert a tab character. However, instead, LT insists on trying to insert some text -- or, even worse, changing the word I have just finished typing into the nearest thing it can match to. To get my tab, I have to press space, and then tab, and then go back and delete the space later.

I love the quality of the autocomplete feature in LT, but is it possible to bind it wholesale to something I don't use for anything else, such as Esc? I don't want Tab to have anything to do with it :)

**Comment by kenny-evitt** [comment]
@mrobbetts Somewhat ironically, you can use autocompletion to check – open your 'user behaviors' file and type "autocomplete" or similar variations; any behaviors should be listed in an autocomplete dropdown.

But, if you can't find a suitable behavior, or there isn't one currently, you can dismiss the autocomplete 'hinter' by hitting <kbd>Esc</kbd>. That should be a lot easier when you want to enter a tab character in a file.

**Comment by mrobbetts** [comment]
> Somewhat ironically, you can use autocompletion to check

I did try that. I can't find anything in there related to `hinting` or `autocomplete`. I'm finding discoverability in LT to be quite difficult though. Perhaps I am doing it wrong. Could you tell me the exact sequence of keypresses you would make to prompt the hinter?

> you can dismiss the autocomplete 'hinter' by hitting Esc.

Oh, if only that were true. You can dismiss it, but if you press Tab again, it just comes back!

**Comment by kenny-evitt** [comment]
@mrobbetts Yeah; there doesn't seem to be any behavior for that. There are two autocomplete behaviors but their names use "auto-complete" not "autocomplete".

I think I figured out what you're seeing; here are my steps to reproduce:

 1. In a file with existing contents, say some code that contains the word `class`, type `cla`. You should see the autocomplete menu with a suggestion of "class".
 2. Hit <kbd>Esc</kbd> to close the autocomplete menu.
 3. Hit <kbd>Tab</kbd> to *try* to enter a tab character. But instead of a tab being entered, the autocomplete menu is shown instead.

I just bothered to check the *keymap* files instead of the *behaviors* files and discovered that the default keymap includes this:

```
 [:editor.keys.normal "tab" :auto-complete]
```

You can add the following to your *user.keymap* file to change the autocomplete keymap to <kbd>Shift</kbd>+<kbd>Tab</kbd> instead:

```
  [:editor.keys.normal "-tab"]
  [:editor.keys.normal "shift-tab" :auto-complete]
```

Now the autocomplete menu won't be shown until you enter <kbd>Shift</kbd>+<kbd>Tab</kbd>. But keep in mind that you will also now you need to enter <kbd>Shift</kbd>+<kbd>Tab</kbd> to *select* an item from the autocomplete menu too.

You could also disable the 'show [autocomplete] on input/changes' behavior by adding the following to your *user.behaviors* file:

```
  [:editor :-lt.plugins.auto-complete/auto-show-on-input]
```

Then the autocomplete menu will only be shown when you explicitly hit <kbd>Shift</kbd>+<kbd>Tab</kbd>.

**Comment by kenny-evitt** [comment]
@mrobbetts If the above doesn't work, just let me know and I'll re-open this issue.

**Comment by Spenhouet** [comment]
I had a similar issue because i didn't know how to trigger the auto-complete at all without input.
Therefor i added the configuration in intellij style:

```
[:editor.keys.normal "-tab"]
[:editor.keys.normal "ctrl-space" :auto-complete]
```

But i would like to only open the auto-complete with `ctrl-space` and not inserting one of them.
Inserting one of the auto-complete suggestions should be done by pressing `enter`.
How to do that?
Is there a documentation on all possible configurations?
