### ISSUE TITLE
workspace does not appear for noobs until file/folder visits a folder, then lacks folder et al tabs

### ISSUE THREAD

**Issue by kennytilton** [LightTable/LightTable#2173]
The LightTable doc talks about select Workspace from the View menu to visit our first folder, and shows tabs for "Folder" and "Recent". 

That does not happen, perhaps because I was a first time user: I went to the File menu and used Open Folder to get going, and thereafter selecting "Workspace" did show me my previously opened folders.

However, at no time have the Folder, Recent, et al options appeared.

**Comment by carocad** [comment]
@kennytilton you are right. Those tabs do not appear in my LT either.

I guess the reason for this is that those images were made with a previous LT version but I can't be sure since the images seem to be from a Mac OS which is not my case. Probably @kenny-evitt could confirm is this is a documentation bug or if it is something specific to Mac.

Note for @kenny-evitt: He refers to the images shown in http://docs.lighttable.com/ under "with the workspace tree (how to open files)".

**Comment by kenny-evitt** [comment]
@kennytilton Those tabs don't exist in the latest versions. Eventually, it'd be nice of us, or anyone really, to update the docs. For anyone interested in doing so, the source for the docs site are in GitHub:

 - [LightTable/docs.lighttable.com: Light Table's official documentation](https://github.com/LightTable/docs.lighttable.com)

I created LightTable/docs.lighttable.com#9 for this.
