### ISSUE TITLE
Certain VIM commands not working correctly with Vim plugin

### ISSUE THREAD

**Issue by briangorman** [LightTable/LightTable#2190]
OS: Fedora 23 64 Bit
LT: .81
VIm plugin .21

What does not work: ":w and "/" for search", probably more things

Steps to reproduce: 

Create lein project. Run lighttable "./light" Install vim plugin. Things may work at this point. Restart lighttable. The aformentioned vim commands no longer work. Some more basic commands work e.g. dd.

The console log is blank, I have no user settings different than the defaults.

**Comment by tgfbikes** [comment]
I am having a similar issue but on OSX except I do get some markup output on what I think is where the eval output displays:

`<span style="font-family: monospace">:</span><input type="text"/><span style="color: #888">`

My work around was to add this code to my user behaviors:

`[:editor :lt.plugins.vim/activate-vim]`

The only draw back to this approach is when I initially start up light table I get the markup output and my keybindings don't work.  I have to go into my user behaviors file and change something ie add white space and save.  Then my key bindings work and I don't get the markup output...yeah, I don't get it either.

**Comment by kenny-evitt** [comment]
@tgfbikes I created [a separate issue](https://github.com/LightTable/Vim/issues/67) that I think might cover the same thing you mention.

**Comment by briangorman** [comment]
tgfbikes, I see the same html output you are seeing as well.

**Comment by tgfbikes** [comment]
kenny-evitt & briangorman,

Do both of you have to edit your user behaviors/keybindings to get anything vim to work?  Have you found a different workaround than mine?

Thank you both.

**Comment by briangorman** [comment]
I am not editing my behaviors/keybindings. Some things work e.g. movement with the hjkl keys.

**Comment by kenny-evitt** [comment]
@briangorman I don't have any problems with `:w` or `/`. I'll try to test on my Ubuntu box soonish and see if I can reproduce your issue. We may need to engage in some 'asynchronous tele-debugging'.

@tgfbikes I need to be able to reproduce the behavior you're observing, but you may have a weird 'environment', e.g. because of #2138. Given that, would you [uninstall LT completely](https://github.com/LightTable/LightTable/issues/1968) (or move all of the LT files to another directory), download the latest version of LT, and then try to reproduce your issue(s)?

**Comment by briangorman** [comment]
@kenny-evitt I no longer use lighttable, as this issue is a show stopper for me. I really like this editor other than this issue. I am willing to do whatever I can to help fix this issue, but given that I am a clojure novice I really need guidance on where to look otherwise this is too time consuming.

**Comment by kenny-evitt** [comment]
@briangorman I think I've reproduced your problem on Linux.

I'm running a build of the latest source on a 64-bit Ubuntu 14.04 box.

 1. I installed the Vim plugin and I confirmed that `/` works as expected.
 2. I quit Light Table.
 3. I re-opened Light Table (I just opened the binary *LightTable*).
 4. I confirmed that some commands, e.g. `dd`, `yy`, `p` work as expected but `:w` and `/` don't. I also saw the same issue as I described in LightTable/Vim#67, i.e. an HTML fragment in the status bar.
 
 Given the HTML fragment in the status bar, I suspect what seems like the same cause as I also described in LightTable/Vim#67, i.e. something is (somehow) selected.

**Comment by kenny-evitt** [comment]
I cloned [the Vim plugin repository](https://github.com/LightTable/Vim) and then added a `console/log` call to the code for the Vim find command. I eval-ed the form, connected to *LightTable-UI* and ... now `/` works as expected.

**Comment by kenny-evitt** [comment]
Alright; I couldn't reproduce my 'fix' just now. This is very weird.

**Comment by kenny-evitt** [comment]
I think I've found a workaround. And maybe a pointer to what's wrong.

If I copy the following line from [the *vim.behaviors* file from the Vim plugin repo](https://github.com/LightTable/Vim/blob/master/vim.behaviors):

```
 [:find-bar :lt.plugins.vim/find-bar-inactive]
```

... then paste it into my *user.behaviors* and save the editor tab for that file, all of the Vim commands work. But like @tgfbikes, I have to add that line after (re-)starting LT, or comment, save, un-comment, re-save, for whatever happens when the behavior is processed to take effect.

The HTML fragment comes from the CodeMirror Vim Javascript – [this line](https://github.com/LightTable/Vim/blob/master/vim.js#L3681):

```
    var searchPromptDesc = '(Javascript regexp)';
```

and `searchPromptDesc` is referenced in [this code](https://github.com/LightTable/Vim/blob/master/vim.js#L1200-L1215):

```
        switch (command.searchArgs.querySrc) {
          case 'prompt':
            var macroModeState = vimGlobalState.macroModeState;
            if (macroModeState.isPlaying) {
              var query = macroModeState.replaySearchQueries.shift();
              handleQuery(query, true /** ignoreCase */, false /** smartCase */);
            } else {
              showPrompt(cm, {
                  onClose: onPromptClose,
                  prefix: promptPrefix,
                  desc: searchPromptDesc,
                  onKeyUp: onPromptKeyUp,
                  onKeyDown: onPromptKeyDown
              });
            }
            break;
```

which is in the `processSearch` function:

```
      processSearch: function(cm, vim, command) {
```

And that seems to be a (big?) part of the problem. Somehow, <kbd>/</kbd> in normal mode is causing the CodeMirror Vim search function to be used instead of the Light Table find feature.

When the search key mapping – <kbd>/</kbd> – is *not* working, [the function `processCommand`](https://github.com/LightTable/Vim/blob/master/vim.js#L1034-L1059) is receiving a 'search' command and when it *is* working it's receiving a 'keyToEx' command instead:

```
      processCommand: function(cm, vim, command) {
        vim.inputState.repeatOverride = command.repeatOverride;
        switch (command.type) {
          case 'motion':
            this.processMotion(cm, vim, command);
            break;
          case 'operator':
            this.processOperator(cm, vim, command);
            break;
          case 'operatorMotion':
            this.processOperatorMotion(cm, vim, command);
            break;
          case 'action':
            this.processAction(cm, vim, command);
            break;
          case 'search':
            this.processSearch(cm, vim, command);
            break;
          case 'ex':
          case 'keyToEx':
            this.processEx(cm, vim, command);
            break;
          default:
            break;
        }
      },
```

[The function `matchCommand` defined on the object `commandDispatcher`](https://github.com/LightTable/Vim/blob/master/vim.js#L955-L1033):

```
    var commandDispatcher = {
      matchCommand: function(key, keyMap, vim) {
        var inputState = vim.inputState;
        var keys = inputState.keyBuffer.concat(key);
        var matchedCommands = [];
        var selectedCharacter;
        for (var i = 0; i < keyMap.length; i++) {
          var command = keyMap[i];
          if (matchKeysPartial(keys, command.keys)) {
            if (inputState.operator && command.type == 'action') {
              // Ignore matched action commands after an operator. Operators
              // only operate on motions. This check is really for text
              // objects since aW, a[ etcs conflicts with a.
              continue;
            }
            // Match commands that take <character> as an argument.
            if (command.keys[keys.length - 1] == 'character') {
              selectedCharacter = keys[keys.length - 1];
              if (selectedCharacter.length>1){
                switch(selectedCharacter){
                  case '<CR>':
                    selectedCharacter='\n';
                    break;
                  case '<Space>':
                    selectedCharacter=' ';
                    break;
                  default:
                    continue;
                }
              }
            }
            // Add the command to the list of matched commands. Choose the best
            // command later.
            matchedCommands.push(command);
          }
        }

        ...
```

... is matching <kbd>/</kbd> only to a 'search' command when it is *not* working and it's matching *three* commands (in `matchedCommands`), the first two of which are 'keyToEx' type commands. When there are multiple matching commands, the code picks the first one that matches the current mode (in our case normal), i.e. the first 'keyToEx' type command.

[Incidentally, I can't type more than one character in the console in Dev Tools inside LT while code is paused at a breakpoint.]

I'll keep exploring this rabbit hole soonish but I think it's clear that, when <kbd>/</kbd> is *not* working, it's because [the `lt_normal_key` extension command](https://github.com/LightTable/Vim/blob/master/src/lt/plugins/vim.cljs#L201-L203) isn't being matched.

**Comment by kenny-evitt** [comment]
I was able to reproduce this just now on a Windows 10 computer [note to me – L]. I'm running the 0.8.1 release and I recently ['uninstalled'](https://github.com/LightTable/LightTable/issues/1968) so that might be why (somehow) I wasn't able to reproduce this earlier on other computers (e.g. where I've been working with source builds of LT and maybe some kind of vestigial code/files that kept this working after someone somehow broke it).

**Comment by adammunoz** [comment]
My workaround is to reload the behaviours:

ctrl+space and type Reload behaviours.

It's easy to do while this bug gets fixed :-)
