### ISSUE TITLE
Same issue as LightTable/issues/1447  in 0.8.1

### ISSUE THREAD

**Issue by mazaltod** [LightTable/LightTable#2272]
Hi,
I open my Tomcat (V6) in a Browser Tab but when I want to access to the manager I got the default Tomcat message to configure tomcat-user.xml : 401 Unauthorized etc....

This file is correctly configured as I can connect directly in my browser or other web tools. 

I supposed I should clear the LT cache, but searching where it is (no more .cache ?) or searching the command to clear the LT cache doesn't give any result.
Thanks to tell me if I am wrong (if the command exists).

David Mazalto.

**Comment by rundis** [comment]
Tx for the report. I believe this could be due to the Chromium WebView from Electron being very aggressively caching. It might have been fixed in this issue upstream (Light Table uses Electron under the hood). https://github.com/electron/electron/pull/6470

Once we upgrade Electron, we can probably pass some flags to the web view thingie.

**Comment by sbauer322** [comment]
For what it is worth, issue https://github.com/LightTable/LightTable/issues/2265 should cover the electron upgrade.

**Comment by mazaltod** [comment]
Ok,
I'll let you close or link this issue.
Thanks.

**Comment by Mouvedia** [comment]
Close as duplicate and reopen #1447.

**Comment by sbauer322** [comment]
Thanks everyone! Closing to reopen #1447 instead.
