### ISSUE TITLE
LightTable freezes because of auto-suggest

### ISSUE THREAD

**Issue by id042013** [LightTable/LightTable#2297]
## Report a Bug

The feature Auto-Suggest that is on by default, makes my app freeze often, usually for up to 10 seconds, but this time I had to kill the process because I could not wait very long.
I don't have any custom setup, I'm quite new using LightTable. The only info I found on the internet related to it is a setting called:

" :editor.keys.hinting.active - Applies when hinting/autocomplete is active"

It would be better to disable this feature by default, or to know how to disable it manually.
Regards.

### Environment

| Info                             | Details |
| -------------------------------- | ------- |
| Light Table version              |     0.8.1    |
| Operating system                 |     10.10.5    |

**Comment by sbauer322** [comment]
I believe we have a long running issue about the performance issues regarding autocomplete here: https://github.com/LightTable/LightTable/issues/2035. Since it does not always happen to all machines, it has been difficult to take care of.

In the meantime, if you wish to disable autocomplete then @rundis's answer on Stack Overflow should help:

http://stackoverflow.com/questions/34883979/turn-off-autocomplete-in-light-table

To summarize and slightly expand on his response:

To access your user.behaviors file, where you would make the change, go to the Command Panel (`Ctrl-Space`), type "Settings: User behaviors", and select the corresponding option. This will open up your `user.behaviors` file, which is where you can make all sorts of changes to Light Table. Simply paste `[:editor :-lt.plugins.auto-complete/textual-hints]` into the block, save, and your autocomplete should be off.

**Comment by id042013** [comment]
Many thanks for answer. The solution works. The topic may be closed.

I only recently read about how to report a bug, so I should have included steps to reproduce the problem. I guess the lag is because the file is very long, although I know nothing about how the auto complete feature is implemented.
