### ISSUE TITLE
Rename 'goto line' command to 'go to line'

### ISSUE THREAD

**Issue by sbauer322** [LightTable/LightTable#2299]
Our command for jumping to a line within a file is 'Editor: Goto line' (Ctrl-L). Unfortunately, if you were not aware of this emacs-derived name then when you search the command panel for 'go to line' or 'jump to line' you are not given any result. The next thought might be that this functionality is a plugin... but searching for those phrases also returns nothing.

As we have an issue with the discover-ability of this functionality, here are some possible possible solutions:

- Change 'Editor: Goto line' to 'Editor: Go to line'... this makes sense as we already have 'Editor: Go to bracket' 
- Extract our 'goto' functionality into a 'go to line' plugin.

A wilder solution would be to improve the searching of our command panel such that it could include results like 'goto' when searching for 'go to'.

**Comment by bruno-oliveira** [comment]
Hi,
I would like to help with this!

**Comment by bruno-oliveira** [comment]
Ive created a pull request

**Comment by bruno-oliveira** [comment]
I have submitted the changes requested and created  more PR, please do check to see if everything is okay.
They all passed the CI tests.

**Comment by bruno-oliveira** [comment]
Any updates?

**Comment by sbauer322** [comment]
Sorry, what I've seen from the PRs looks good so far, but I won't be able to take a proper look at it until late tonight.

My only concern is that it is more common to simply have one pull request containing multiple relevant commits rather than multiple relevant pull requests containing single changes... would you mind condensing the pull requests into one? Everything else seemed okay otherwise.

**Comment by bruno-oliveira** [comment]
How can I do that "condensing"? I've cloned the repo to my local machine but when I try to push I get an error, so Im doing it in the web interface...

**Comment by rundis** [comment]
Did you follow a workflow similar to this: https://gist.github.com/Chaser324/ce0505fbed06b947d962
 ? 
You really should create a branch when working on pull requests. Please create one consolidated PR which will make all our lifes easier ! Oh and tx for your efforts, sorry to be a stickler :-)

**Comment by bruno-oliveira** [comment]
Hi @Magnus,

Yes, I've created a consolidated PR already and will follow up the work. I
went rest until this is merged in the master branch

Em 30/12/2016 09:10, "Magnus Rundberget" <notifications@github.com>
escreveu:

Did you follow a workflow similar to this: https://gist.github.com/
Chaser324/ce0505fbed06b947d962
?
You really should create a branch when working on pull requests. Please
create one consolidated PR which will make all our lifes easier ! Oh and tx
for your efforts, sorry to be a stickler :-)

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/LightTable/LightTable/issues/2299#issuecomment-269748794>,
or mute the thread

**Comment by bruno-oliveira** [comment]
Hi,
I've added some commits to fix what we discussed... I hope all is good now!

**Comment by bruno-oliveira** [comment]
For reference, commits have been squashed and the issue is in progress of being solved.

**Comment by sbauer322** [comment]
PR https://github.com/LightTable/LightTable/pull/2306 addresses this issue and has been merged. Thanks again, @bruno-oliveira!
