### ISSUE TITLE
Block commenting?

### ISSUE THREAD

**Issue by belucid** [LightTable/LightTable#429]
Does Light Table have the ability to highlight a block and convert it all to a comment (or uncomment if it's already commented). I forgot to mention it, but in the survey you just conducted which asked what is keeping you from using Light Table as your primary editor, this is a big one for me.

**Comment by Joshfindit** [comment]
For future generations, this one way to accomplish pressing pmeta (command on OSX) + / while text is highlighted in order to toggle highlighting.

    [:editor.active "pmeta-/" :toggle-comment-selection]

(add this line through Light Table by pressing ctrl+space, then choosing "Settings: User keymap")

Is this possibly too much hand-holding for developers; for sure. But I would have appreciated this post when working to make it happen myself.
Granted, I'm a newbie.
