### ISSUE TITLE
Use the xdg basedir spec on Linux

### ISSUE THREAD

**Issue by jleclanche** [LightTable/LightTable#557]
Reference spec:
http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

TLDR: Use $XDG_CACHE_HOME/lighttable/ (fallback: ~/.cache/lighttable/), $XDG_DATA_HOME (~/.local/share/lighttable/) and $XDG_CONFIG_HOME (~/.config/lighttable/) instead of ~/.lighttable/.
Keeps home directory clean.

Looking at what's in ~/.lighttable, all of it should go in ~/.local/share/lighttable (XDG_DATA_HOME) except cache and settings (going in XDG_CACHE_HOME and XDG_CONFIG_HOME respectively.

**Comment by kenny-evitt** [comment]
We can re-open this if anyone is willing to submit a PR for the relevant changes.

**Comment by jleclanche** [comment]
If you're still accepting PRs fixing this, then why close the bug? *shrugs*

**Comment by kenny-evitt** [comment]
@jleclanche I closed this to cleanup the list of open issues. If no one's interested in working on this, why keep it open?

More generally, because the original team has moved on to another project, the only changes that are going to be made are those that the remaining contributors are interested in in working on. I'm running LT on Linux, but this isn't a priority for me.

There's no definitive interpretation of what an open issue means exactly but I don't want to signal or indicate that this is something we've committed to working on.

That's all. I'm willing to help anyone that wants to work on this tho – and if anyone is, I'll re-open this too. Are you interesting in looking into this?

If you are interested, take a look at [this issue](https://github.com/LightTable/LightTable/issues/1968). We're using the Electron default user data directory currently. Do you have suggestions on what we should be doing differently? Should we report this upstream to Electron?

**Comment by jleclanche** [comment]
I don't know about electron, but as far as the spec goes, config should at the very least be in `$XDG_CONFIG_HOME/<project>/...` or some form of it. You can respect the spec to various extents so it depends on the complexity you want to introduce.

**Comment by kenny-evitt** [comment]
Huh – here's [the relevant Electron doc](https://github.com/atom/electron/blob/master/docs/api/app.md#appgetpathname) now:

>  * `appData` Per-user application data directory, which by default points to:
>   * ...
>   * `$XDG_CONFIG_HOME` or `~/.config` on Linux

[It looks like this has been in Electron since version 0.20.7](https://github.com/atom/electron/commit/8aa5b97c614994c07335e823854ab6a702a96228) and we're currently on 0.31.1.

Would you try building the latest source and checking where it creates the directory?

**Comment by jleclanche** [comment]
I can't right now, sorry. I'll leave it up to someone else to try it.
