### ISSUE TITLE
Milestones for other languages

### ISSUE THREAD

**Issue by elsewares** [LightTable/LightTable#57]
More of a question than an issue - I enjoy the updates and I downloaded the new playground, but I'm really waiting for Python integration, since Clojure isn't in my repertoire.  When will Python REPL be in place, and are there any plans for Ruby, Node or other REPL-capable languages to be supported?

I'd mark this as a question if I knew how - thanks.

**Comment by standinga** [comment]
+ php

**Comment by snopboy** [comment]
PHP +1

**Comment by rundis** [comment]
rather than +1'ing this issue with php... how about contributing to this plugin instead ?
https://github.com/thierrymarianne/LightTable-PHP

**Comment by snopboy** [comment]
@rundis I wish I could. The only language I know (beside markup/cascading) is PHP and even in that I'm a beginner, can't really see how I could contribute considering my 'skill set' and experience in programming.

I came across Light Table by accident and really thought it will be useful to have PHP support, without it I personally wont be able to use it because PHP is the only language I know, although barely.

You could see my level in PHP and programming in general in my only repository, started this project to both learn PHP more and OOP, yeah I'm that bad in programming lol, I will improve over time.

**Comment by rundis** [comment]
@snopboy Fair enough. The plugin I mentioned provides a little php support (eval of simple statements).
The Light Table distribution will likely never ship with any php support (bar syntax highlighting). So php support will have to come from the community through a plugin(s). I would suggest you raise issues with the plugin I linked to in my last reply if you have feature requests, ideas in terms of what support you are looking for etc.

**Comment by kenny-evitt** [comment]
@snopboy You should be able to install the plugin that @rundis linked-to from the plugin manager in Light Table.
