### ISSUE TITLE
Vertical console window 

### ISSUE THREAD

**Issue by roper79** [LightTable/LightTable#607]
Possibility to make Console window a vertical tab

**Comment by Muffo** [comment]
@ibdknox thanks for the suggestion.
However I think that this is not very straightforward for people that are new to this editor.

Also, the fact that the console is hidden by default makes thing even more complicated for those who are not familiar with Clojure, like me.
Yesterday I spent an awful lot of time trying to understand why the "hello world" was not working.
Eventually I discovered that the reason was going straight to the console, that by default is not visible and I didn't even know that existed until I made some search online...

Maybe the accessibility of the console could be improved in general :)

**Comment by kenny-evitt** [comment]
@Muffo The console should be shown as soon as an error is logged – or at least that's what I *think* it used to do. I created [a new issue](https://github.com/LightTable/LightTable/issues/1948) for implementing that (or fixing whatever broke it, if it previously did that).
