### ISSUE TITLE
Eval of any .clj file fails

### ISSUE THREAD

**Issue by dpathakj** [LightTable/LightTable#700]
Evaling clojure files fails somewhat silently.

Minimal steps to reproduce:
1. echo "1" > foo.clj
2. open foo.clj in Light Table
3. With the cursor over 1, Cmd + Shift + Enter.

Result: nothing happens (the 1 doesn't eval to 1, as it should). A stack trace in the lower right documents a failure of some kind.

If I try function calls like (+ 1 2) I get an inline "clojure.lang.Compiler$CompilerException: java.lang.RuntimeException: Unable to resolve symbol: + in this context" but I'm fairly sure it's just due to the same failing setup.

I'm on OS X 10.8. 

Stack trace:

bootstrap.js[16107]:  
nil
TypeError: Cannot read property 'addEventListener' of undefined
    at Function.on (core/node_modules/codemirror/codemirror.js:5241:16)
    at Function.<anonymous> (app://lighttable/core/node_modules/lighttable/bootstrap.js:25714:14)
    at c (app://lighttable/core/node_modules/lighttable/bootstrap.js:6043:14)
    at a (app://lighttable/core/node_modules/lighttable/bootstrap.js:6072:18)
    at a (app://lighttable/core/node_modules/lighttable/bootstrap.js:19291:142)
    at b (app://lighttable/core/node_modules/lighttable/bootstrap.js:19303:14)
    at Function.<anonymous> (app://lighttable/core/node_modules/lighttable/bootstrap.js:25725:24)
    at c (app://lighttable/core/node_modules/lighttable/bootstrap.js:6043:14)
    at a (app://lighttable/core/node_modules/lighttable/bootstrap.js:6072:18)
    at lt.object.raise_STAR_ (app://lighttable/core/node_modules/lighttable/bootstrap.js:19170:502)

**Comment by raould** [comment]
uh, hmm, I only just downloaded LT 0.7.2 to this macbook os x 10.9, and i wrote test.clj that has only the number 2 in it, and evaluating it causes things to blow up just like this issue reports. Adding "(ns my-namespace)" in doesn't seem to help, LT seems to be fubar now and just keeps writing such errors into the console.

**Comment by kenny-evitt** [comment]
@raould I can reproduce this, but I'm not sure that this isn't a 'by-design bug'. Clojure isn't typically evaluated as naked expressions in text files, even if they have a *.clj* extension. Most (?) Clojure code is part of a Leiningen project and every code file defines a namespace in the project. Otherwise, code is evaluated 'live' in a REPL.

Interestingly, the expression `2` isn't *visually* evaluated in a Clojure "InstaREPL" tab in Light Table, but then again `2` evaluates to itself anyways so this isn't a significant missing feature. And `(+ 1 2)` evaluated fine, even after I tried reproduced this issue. I can also evaluate that same expression in the *test.clj* file I created after I run the "Instarepl: Make current editor an instarepl" command.

Are you having problems evaluating expressions that don't evaluate to themselves (i.e. ["strings, numbers, characters, true, false, nil and keywords"](http://clojure.org/evaluation))?

**Comment by raould** [comment]
Thanks! I can grok that there are things even Clojure wouldn't like :-), so neither should LT. But I guess I'd want it to just report the Clojure error, and not additionally add in whatever confusing extra layers of errors it does with all the "TypeError: Cannot read property 'addEventListener' of undefined" stuff? Since that makes it look like LT is just borked making it harder for users to figure out where to go from there.
