### ISSUE TITLE
Wrong caption on the button for folder dialog

### ISSUE THREAD

**Issue by can3p** [LightTable/LightTable#928]
If I click on folder link on the sidebar open dialog appears but instead of "open" button I see the confirmation button with caption "Upload"

LT 0.5.20, Mac OS X 10.7.5

**Comment by subunit** [comment]
I am still having this issue in the current version of LT (0.7.2) as well as the "developer" version, since it seems to include the same version of node-webkit (v0.8.4). The [LT node-webkit repo](https://github.com/LightTable/node-webkit) includes [the fix](https://github.com/LightTable/node-webkit/commit/50c298c5aaa6bc831ac0d9fee1600b31e237c467), however, so I think LT just needs to be rebuilt to fix this bug? (After much pain, I was able to recompile node-webkit myself and hack it back into LT to verify that the bug was indeed fixed - see [here](https://www.waitingforthefuture.org/2015/01/05/building-lighttable-with-an-updated-node-webkit-on-osx/) for agonizing details)

Side note, this bug freaked me out when I first opened LightTable, as I assumed that it was going to be uploading my folder contents to some unknown place. I'm probably not the only one.
